"""Kokoro voice and language constants for the control window."""

from __future__ import annotations

KOKORO_VOICES: list[tuple[str, str]] = [
    ("af_heart", "Heart — American female, warm (default)"),
    ("af_alloy", "Alloy — American female"),
    ("af_aoede", "Aoede — American female"),
    ("af_bella", "Bella — American female"),
    ("af_jessica", "Jessica — American female"),
    ("af_kore", "Kore — American female"),
    ("af_nicole", "Nicole — American female"),
    ("af_nova", "Nova — American female"),
    ("af_river", "River — American female"),
    ("af_sarah", "Sarah — American female"),
    ("af_sky", "Sky — American female"),
    ("am_adam", "Adam — American male"),
    ("am_echo", "Echo — American male"),
    ("am_eric", "Eric — American male"),
    ("am_fenrir", "Fenrir — American male"),
    ("am_liam", "Liam — American male"),
    ("am_michael", "Michael — American male"),
    ("am_onyx", "Onyx — American male"),
    ("am_puck", "Puck — American male"),
    ("am_santa", "Santa — American male"),
    ("bf_alice", "Alice — British female"),
    ("bf_emma", "Emma — British female"),
    ("bf_isabella", "Isabella — British female"),
    ("bf_lily", "Lily — British female"),
    ("bm_daniel", "Daniel — British male"),
    ("bm_fable", "Fable — British male"),
    ("bm_george", "George — British male"),
    ("bm_lewis", "Lewis — British male"),
    ("ef_dora", "Dora — Spanish female"),
    ("em_alex", "Alex — Spanish male"),
    ("em_santa", "Santa — Spanish male"),
    ("ff_siwis", "Siwis — French female"),
    ("hf_alpha", "Alpha — Hindi female"),
    ("hf_beta", "Beta — Hindi female"),
    ("hm_omega", "Omega — Hindi male"),
    ("hm_psi", "Psi — Hindi male"),
    ("if_sara", "Sara — Italian female"),
    ("im_nicola", "Nicola — Italian male"),
    ("jf_alpha", "Alpha — Japanese female"),
    ("jf_gongitsune", "Gongitsune — Japanese female"),
    ("jf_nezumi", "Nezumi — Japanese female"),
    ("jf_tebukuro", "Tebukuro — Japanese female"),
    ("jm_kumo", "Kumo — Japanese male"),
    ("pf_dora", "Dora — Brazilian Portuguese female"),
    ("pm_alex", "Alex — Brazilian Portuguese male"),
    ("pm_santa", "Santa — Brazilian Portuguese male"),
    ("zf_xiaobei", "Xiaobei — Mandarin Chinese female"),
    ("zf_xiaoni", "Xiaoni — Mandarin Chinese female"),
    ("zf_xiaoxiao", "Xiaoxiao — Mandarin Chinese female"),
    ("zf_xiaoyi", "Xiaoyi — Mandarin Chinese female"),
    ("zm_yunjian", "Yunjian — Mandarin Chinese male"),
    ("zm_yunxi", "Yunxi — Mandarin Chinese male"),
    ("zm_yunxia", "Yunxia — Mandarin Chinese male"),
    ("zm_yunyang", "Yunyang — Mandarin Chinese male"),
]

LANGUAGES: list[tuple[str, str]] = [
    ("en-us", "English (US)"),
    ("en-gb", "English (UK)"),
    ("es", "Spanish"),
    ("fr-fr", "French"),
    ("hi", "Hindi"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("pt-br", "Portuguese (Brazil)"),
    ("zh", "Chinese (Mandarin)"),
]
